---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- command: hostname
  register: hostname
  changed_when: false

- debug:
    var: ansible_os_family

- name: Display all variables/facts
  debug:
    var: hostvars[inventory_hostname]
