---
- name: simple Plabook to provision fresh raspberrypi
  hosts: all
  roles:
    - { role: bassinator.localisation, loc_timezone: Europe/Zurich, keyboard_layout: ch, keyboard_variant: de }
    - { role: bassinator.mosquitto, tags: ["epic", "mqtt"] }
    - { role: bassinator.nodered, tags: ["epic", "mqtt"] }
    - { role: bassinator.simplehttp,  installation_os_user: pi, installation_os_group: pi, tags: ["epic", "mqtt", "webvr"] }
    - { role: bassinator.scratch_mqtt,  installation_os_user: pi, installation_os_group: pi, tags: ["epic", "mqtt"] }
    - { role: bassinator.autoarchive, installation_os_user: pi, installation_os_group: pi, tags: ["epic", "scratch"] }
    - { role: bassinator.usbbackup, installation_os_user: pi, installation_os_group: pi, tags: ["epic"] }
    - { role: bassinator.tigerjython, installation_os_user: pi, installation_os_group: pi, tags: ["epic", "python"] }
  remote_user: pi
  become: yes

  post_tasks:
    - git:
        repo: https://github.com/Bassinator/learning_webvr.git
        dest: /home/pi/www/vr
