---
- name: simple Plabook to provision fresh raspberrypi
  hosts: all
  vars: 
    installation_os_user: pi
    installation_os_group: pi
  roles:
    - { role: bassinator.localisation, loc_timezone: Europe/Zurich, keyboard_layout: ch, keyboard_variant: de }
    - { role: bassinator.mosquitto, tags: ["epic", "mqtt"] }
    - { role: bassinator.nodered, tags: ["epic", "mqtt"] }
    - { role: bassinator.simplehttp, tags: ["epic", "mqtt", "webvr"] }
    - { role: bassinator.scratch_mqtt, tags: ["epic", "mqtt"] }
    - { role: bassinator.autoarchive, tags: ["epic", "scratch"] }
    - { role: bassinator.usbbackup, tags: ["epic"] }
    - { role: bassinator.tigerjython, tags: ["epic", "python"] }
  remote_user: pi
  become: yes

  post_tasks:
    - command: git clone https://github.com/Bassinator/learning_webvr.git /home/pi/www/vr
      args:
        creates: /home/pi/www/vr
