---

- name: Playbook to provision docker as raspberry provisioner
  hosts: localhost
  roles:
    - { role: centos.nmap }
  remote_user: pi
  become: yes


- name: simple Plabook to provision fresh raspberrypi
  hosts: raspberrys
  environment:
    HTTP_PROXY: '{{ http_proxy }}'
    HTTPS_PROXY: '{{ https_proxy }}'
  roles:
    - { role: pi.test }
    # - { role: bassinator.mosquitto }
    # - { role: bassinator.nodered }
    - { role: bassinator.autoarchive, installation_os_user: pi, installation_os_group: pi }
    # - { role: bassinator.simplehttp,  installation_os_user: pi, installation_os_group: pi }
    - { role: bassinator.usbbackup, installation_os_user: pi, installation_os_group: pi }
    - { role: bassinator.tigerjython, installation_os_user: pi, installation_os_group: pi }
    # - { role: pi.wifi }
    # - { role: pi.base }
  remote_user: pi
  become: yes
