- debug:
    var: ansible_os_family

# - include_tasks: installOsPackages-RedHat.yml
#   when: ansible_os_family == 'RedHat'
#
- include_tasks: installOsPackages-Debian.yml
#   when: ansible_os_family == 'Debian'

# - name: update packages
#   yum:
#     name: '*'
#     state: latest
#   when: packages == "latest"
#   register: update
#
# - name: install the package, force upgrade
#   pip:
#     name: 'pip'
#     extra_args: '--upgrade'
# - name: install pip packages
#   pip:
#     name: "{{ item }}"
#     state: present
#   with_items: "{{ pip_packages }}"

- name: Make sure mosquitto is started and enabled to start on boot
  systemd:
    name: 'mosquitto'
    state: 'started'
    enabled: 'yes'
